name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set date tag
        id: date_tag
        run: echo "::set-output name=tag::$(date +%s)"

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag oxygen-cs-grp01-eq04:${{ steps.date_tag.outputs.tag }}
      
      - name: Docker push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker logout
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag oxygen-cs-grp01-eq04:${{ steps.date_tag.outputs.tag }} $DOCKER_USERNAME/oxygen-cs-grp01-eq04:${{ steps.date_tag.outputs.tag }}
          docker push $DOCKER_USERNAME/oxygen-cs-grp01-eq04:${{ steps.date_tag.outputs.tag }}
  test:
    needs: build
    name: Pytest in Pipenv
    runs-on: ubuntu-latest 
    container:
      image: abder123alg/oxygen-cs-grp01-eq04:${{ jobs.build.steps.date_tag.outputs.tag }}
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
          pipenv run pytest tests/