name: Pytest with Pipenv & Docker
# workflow triggered by any push on any branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    # runs within your Docker container
    container:
      image: docker://abder123alg/oxygen-cs-grp01-eq04:latest
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
          pipenv run pytest tests/